title: memo
description: 個人用 講義ノート
theme: just-the-docs

url: https://sato3205.github.io
baseurl: /memo

search_enabled: true
heading_anchors: true

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: false

aux_links:
  GitHub:
    - https://github.com/sato3205/memo

# just-the-docs 推奨
color_scheme: light

# ページ内の見出しに自動で目次を出しやすくする
toc_enabled: true

# 「編集」リンク（任意）
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/sato3205/memo"
gh_edit_branch: "main"

nav_enabled: true
nav_fold: true

